---
# required
accessToken: "" # create this under API Tokens. Set permission to EDIT Zone.DNS
domain: "example.com" # the domain that the account controls
recordName: "ip.example.com" # the record name, use domain name for @
recordType: "A" # type of record
jsonIPService: "http://ip-api.com/json/" # a web service returning json which includes the ip
jsonQuery: "query" # gjson query to get the ip address

# these extra values can be set to make number of requests lower if you update the same record often
# run the command without these, and you'll get them in the log
#zoneId: "" # zone id for the domain
#dnsId: "" # id of the specific dns record
